spring:     
  cloud:
    gateway:
      routes:
      - id: item-catalog-service
        uri: lb://items/**
        predicates:
        - Path=/items
      - id: edge-service
        uri: lb://edge-service/**
        predicates:
        - Path=/brand-items1
     
