spring:     
  cloud:
    gateway:
      routes:
      - id: item-catalog-service
        uri: lb://item-catalog-service:8088
        predicates:
        - Path=/items
      - id: edge-service
        uri: lb://edge-service:8089
        predicates:
        - Path=/top-brands
     
