server:
  port: 8091
spring:     
  cloud:
    gateway:
      routes:
      - id: item-catalog-service
        uri: lb://item-catalog-service
        predicates:
        - Path=/items
      - id: edge-service
        uri: lb://edge-service
        predicates:
        - Path=/top-brands
   
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true    
